### PR TITLE
rust: add support for finding packages in virtual workspaces

### LINKED ISSUE #1174: `language: rust` fails with virtual workspaces
### Summary

`typos` and `committed` worked with pre-commit until I switched to virtual workspaces (which I did to make python packages to allow my hooks to be installed that way).
- crate-ci/typos#1436
- crate-ci/committed#453

Apparently, this carried forward to prek when it added support for `language: rust`

### Platform

Linux 6.16.3-76061603-generic x86_64 GNU/Linux

### Version

As of #989

### .pre-commit-config.yaml

_No response_

### Log file

_No response_

### PR DESCRIPTION
**Pull request by lmmx**
- Follow-on from #989
- Fixes #1174 (which pre-commit never supported)

## What's new:

- ability to run the `typos-src` hook in the crate-ci/typos repo
- various new unit tests covering different types of workspace including virtual workspaces
- use `cargo_metadata` to get package binary info robustly (+1.22% or +0.2MB binary size)

## Status

- Ready to review (merge if happy)

### CODE REVIEW

File: src/languages/rust/rust.rs [hunk 1]
```diff
@@ -40,6 +40,81 @@ fn extract_package_name(content: &str) -> Option<String> {
...
+
+/// Extract binary names from `[[bin]]` sections in Cargo.toml.
+fn extract_bin_names(content: &str) -> Vec<String> {
+    let mut names = Vec::new();
+    let mut in_bin_section = false;
+
+    for line in content.lines() {
+        let trimmed = line.trim();
+
+        if trimmed == "[[bin]]" {
```
Comment (epage) [inline src/languages/rust/rust.rs]: Would it work to call `cargo metadata --no-deps` (wrapped via [`cargo_metadata` package](https://docs.rs/cargo_metadata/latest/cargo_metadata/))  to discover all packages and their bins?

Comment (lmmx) [reply src/languages/rust/rust.rs]: Yep I'm sure it would :slightly_smiling_face: We've tried to avoid adding deps (especially when language-specific) but I can give it a try and see what cargo bloat reports

Comment (lmmx) [reply src/languages/rust/rust.rs]: I re-rolled into one commit so we have a 'save point', when I added `cargo_metadata` there's only 1 new cargo lock dep (`cargo-platform`) which I take to mean we already build the rest in the crate tree

```diff
diff --git a/Cargo.lock b/Cargo.lock
index 65ca431..d6311ff 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -368,6 +368,29 @@ dependencies = [
  "serde_core",
 ]
 
+[[package]]
+name = "cargo-platform"
+version = "0.3.1"
+source = "registry+https://github.com/rust-lang/crates.io-index"
+checksum = "122ec45a44b270afd1402f351b782c676b173e3c3fb28d86ff7ebfb4d86a4ee4"
+dependencies = [
+ "serde",
+]
+
+[[package]]
+name = "cargo_metadata"
+version = "0.23.1"
+source = "registry+https://github.com/rust-lang/crates.io-index"
+checksum = "ef987d17b0a113becdd19d3d0022d04d7ef41f9efe4f3fb63ac44ba61df3ade9"
+dependencies = [
+ "camino",
+ "cargo-platform",
+ "semver",
+ "serde",
+ "serde_json",
+ "thiserror 2.0.17",
+]
+
 [[package]]
 name = "cc"
 version = "1.2.47"
@@ -1842,6 +1865,7 @@ dependencies = [
  "async-compression",
  "axoupdater",
  "bstr",
+ "cargo_metadata",
  "clap",
  "clap_complete",
  "ctrlc",
diff --git a/Cargo.toml b/Cargo.toml
index 0d54684..f6347f5 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -97,6 +97,7 @@ tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
 unicode-width = { version = "0.2.0" }
 which = { version = "8.0.0" }
 glob = "0.3.3"
+cargo_metadata = "0.23.1"
 
 [target.'cfg(unix)'.dependencies]
 prek-pty = { workspace = true }
```

(Just breaking for dinner!)

Comment (epage) [reply src/languages/rust/rust.rs]: If bloat is a problem, you can always call `cargo metadata` yourself and define only the set of serde types you need to read the output.  Likely best once you have a working solution with it and if there the need to optimize it is worth it.

Comment (lmmx) [reply src/languages/rust/rust.rs]: > +1.22%

I think that's reasonable. This allows us to throw out a lot of processing code (3d3ce36)

**Comment by j178** [comment]
Thanks!

File: src/languages/rust/rust.rs [hunk 2]
```diff
@@ -179,8 +214,28 @@ impl LanguageImpl for Rust {
                     .check(true)
                     .output()
                     .await?;
+            } else if lib_deps.is_empty() {
+                // For workspace members without lib deps, use cargo build + copy
+                // (cargo install doesn't work well with virtual workspaces)
```
Comment (epage) [inline src/languages/rust/rust.rs:219]: What problem is this? 

(context: also a cargo team member)

Comment (lmmx) [reply src/languages/rust/rust.rs:219]: Here I was trying to install a specific binary from its path whose metadata I got from the workspace, and tried a few ways. I ended up deciding that it’s best to just build and copy the binary rather than try to point to the subpath. I forget exactly what error I was getting but this looked like the best way to do it.

Comment (epage) [reply src/languages/rust/rust.rs:219]: I would assume that the same install approach should be used regardless of whether the package is in the root of a workspace or not.  It keeps the code simpler and makes it faster to discover the root cause of undesired behavior.

The following seemed to work for me
```console
cargo +nightly install -Zunstable-options --dry-run --path ../typos/crates/typos-cli/ --bins
```
(`-Z` is for `--dry-run` to work)

Comment (lmmx) [reply src/languages/rust/rust.rs:219]: Hmmm yes let me throw this in an issue so I can come back to it...

Edit: opened #1191 to track
